#!/usr/bin/env python
#
# BlackDuck Task Service over Bluetooth
#

import logging

from blackduck.server import Server

log = logging.getLogger(__name__)

if __name__ == '__main__':
    try:
        server = Server()
        server.run()
    finally:
        log.info('Server shutdown.')
