#!/usr/bin/env python
#
# BlackDuck Task Service over Bluetooth
#

import logging

from blackduck.btservice import BluetoothService
from blackduck.events import EventBus, EventBusLogOutput

log = logging.getLogger(__name__)

if __name__ == '__main__':
    try:
        eventbus = EventBus()

        # Log everything to the event bus.
        logging.getLogger().addHandler(logging.StreamHandler(EventBusLogOutput(eventbus)))

        # TODO: Start screen manager.

        # Start listening for Bluetooth service connections.
        btservice = BluetoothService(eventbus)
        btservice.start()

        # TODO: Start GTK app.
    finally:
        log.info('Server shutdown.')
